In [11]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [12]:
catch = pd.read_csv('pokemon (2).csv')

catch

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [13]:
clean = pd.read_csv("pokemon_clean.csv")

clean

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,hp,name,pokedex_number,sp_attack,sp_defense,speed,type1,type2,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,45,Bulbasaur,1,65,65,45,grass,poison,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,60,Ivysaur,2,80,80,60,grass,poison,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,80,Venusaur,3,122,120,80,grass,poison,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,39,Charmander,4,60,50,65,fire,NaN,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,58,Charmeleon,5,80,65,80,fire,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,97,Celesteela,797,107,101,61,steel,flying,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,59,Kartana,798,59,31,109,grass,steel,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,223,Guzzlord,799,97,53,43,dark,dragon,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,97,Necrozma,800,127,89,79,psychic,NaN,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,80,Magearna,801,130,115,65,steel,fairy,7,1

In [14]:
indexes_to_drop = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

clean_dropped = clean.drop(clean.columns[indexes_to_drop], axis=1)

clean_dropped

,abilities,name,pokedex_number,sp_attack,sp_defense,speed,type1,type2,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",Bulbasaur,1,65,65,45,grass,poison,1,0
1,"['Overgrow', 'Chlorophyll']",Ivysaur,2,80,80,60,grass,poison,1,0
2,"['Overgrow', 'Chlorophyll']",Venusaur,3,122,120,80,grass,poison,1,0
3,"['Blaze', 'Solar Power']",Charmander,4,60,50,65,fire,NaN,1,0
4,"['Blaze', 'Solar Power']",Charmeleon,5,80,65,80,fire,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],Celesteela,797,107,101,61,steel,flying,7,1
797,['Beast Boost'],Kartana,798,59,31,109,grass,steel,7,1
798,['Beast Boost'],Guzzlord,799,97,53,43,dark,dragon,7,1
799,['Prism Armor'],Necrozma,800,127,89,79,psychic,NaN,7,1
800,['Soul-Heart'],Magearna,801,130,115,65,steel,fairy,7,1

In [15]:
catch = catch.rename(columns={'Name': 'name'})
clean_dropped = clean_dropped.rename(columns={'is_legendary': 'Legendary'})

In [31]:
pokemon = pd.merge(
    clean_dropped[['name', 'pokedex_number', 'type1', 'type2', 'generation', 'Legendary']],
    catch[['name', 'Type 1', 'Type 2', 'Generation', 'Legendary']],
    on='name',
    how='right',
    suffixes=('_clean', '_catch')
)

pokemon = pokemon.loc[:, ~pokemon.columns.duplicated()]

pokemon

,name,pokedex_number,type1,type2,generation,Legendary_clean,Type 1,Type 2,Generation,Legendary_catch
0,Bulbasaur,1.0,grass,poison,1.0,0.0,Grass,Poison,1,False
1,Ivysaur,2.0,grass,poison,1.0,0.0,Grass,Poison,1,False
2,Venusaur,3.0,grass,poison,1.0,0.0,Grass,Poison,1,False
3,VenusaurMega Venusaur,NaN,NaN,NaN,NaN,NaN,Grass,Poison,1,False
4,Charmander,4.0,fire,NaN,1.0,0.0,Fire,NaN,1,False
...,...,...,...,...,...,...,...,...,...,...
795,Diancie,719.0,rock,fairy,6.0,1.0,Rock,Fairy,6,True
796,DiancieMega Diancie,NaN,NaN,NaN,NaN,NaN,Rock,Fairy,6,True
797,HoopaHoopa Confined,NaN,NaN,NaN,NaN,NaN,Psychic,Ghost,6,True
798,HoopaHoopa Unbound,NaN,NaN,NaN,NaN,NaN,Psychic,Dark,6,True
799,Volcanion,721.0,fire,water,6.0,1.0,Fire,Water,6,True

In [36]:
pokemon

,name,pokedex_number,type1,type2,generation,Type 1,Type 2,Generation
0,Bulbasaur,1.0,grass,poison,1.0,Grass,Poison,1
1,Ivysaur,2.0,grass,poison,1.0,Grass,Poison,1
2,Venusaur,3.0,grass,poison,1.0,Grass,Poison,1
3,VenusaurMega Venusaur,NaN,NaN,NaN,NaN,Grass,Poison,1
4,Charmander,4.0,fire,NaN,1.0,Fire,NaN,1
...,...,...,...,...,...,...,...,...
795,Diancie,719.0,rock,fairy,6.0,Rock,Fairy,6
796,DiancieMega Diancie,NaN,NaN,NaN,NaN,Rock,Fairy,6
797,HoopaHoopa Confined,NaN,NaN,NaN,NaN,Psychic,Ghost,6
798,HoopaHoopa Unbound,NaN,NaN,NaN,NaN,Psychic,Dark,6
799,Volcanion,721.0,fire,water,6.0,Fire,Water,6

In [37]:
pokemon.to_csv("pokemon.csv")
pokemon

,name,pokedex_number,type1,type2,generation,Type 1,Type 2,Generation
0,Bulbasaur,1.0,grass,poison,1.0,Grass,Poison,1
1,Ivysaur,2.0,grass,poison,1.0,Grass,Poison,1
2,Venusaur,3.0,grass,poison,1.0,Grass,Poison,1
3,VenusaurMega Venusaur,NaN,NaN,NaN,NaN,Grass,Poison,1
4,Charmander,4.0,fire,NaN,1.0,Fire,NaN,1
...,...,...,...,...,...,...,...,...
795,Diancie,719.0,rock,fairy,6.0,Rock,Fairy,6
796,DiancieMega Diancie,NaN,NaN,NaN,NaN,Rock,Fairy,6
797,HoopaHoopa Confined,NaN,NaN,NaN,NaN,Psychic,Ghost,6
798,HoopaHoopa Unbound,NaN,NaN,NaN,NaN,Psychic,Dark,6
799,Volcanion,721.0,fire,water,6.0,Fire,Water,6